SHELL := /bin/bash
.PHONY: figs modeling_figs

figs: correlated-pi-examples.png \
		close_divergence_tree.png \
		far_divergence_tree.png \
		greatapes_pi.png \
		greatapes_dxy.png \
		landscapes_cover.png \
		scatter-examples-pidxy_win-size_1000000_merged-mask_True_state_all_curr_all_prop-acc_0.4.png \
		trees-with-dt.png \
		cor-pidxy-dT_data.png \
		demog_tubes_greatapes.png \
		corr-pidxy-land-panel_neutral.png \
		cor-pidxy-dT_selected-mutvar-sims_1.png \
		cor-pidxy-dT_selected-negative.png \
		cor-pidxy-dT_selected-positive.png \
		cor-pidxy-dT_selected-both.png


include ../../rules.mk
